obj-y	+=  oppo_project/
obj-y	+=  oppo_devinfo/
obj-y   +=  oppo_als_cali_value/
obj-y	+=  oppo_sensorinfo/
obj-y	+=  oppo_gpio/

#ifdef CONFIG_VENDOR_EDIT
obj-$(CONFIG_OPPO_SHUTDOWN_DETECT)	+=  oppo_shutdown_detect/
#endif /* CONFIG_VENDOR_EDIT */
obj-$(CONFIG_OPPO_PHOENIX)     +=  oppo_phoenix/

#ifdef CONFIG_VENDOR_EDIT
obj-y     +=  oppo_healthinfo/
#endif /* CONFIG_VENDOR_EDIT */

#ifdef CONFIG_VENDOR_EDIT
#obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/
obj-y     +=  oppo_mdmrst/
#endif /* CONFIG_VENDOR_EDIT */

#ifdefine CONFIG_VENDOR_EDIT
obj-y +=  oppo_kevent_feedback/
#endif /* CONFIG_VENDOR_EDIT */
